config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :visits
  devise_for :users
  

  root 'static#homepage'

  get 'users/:id', to: "users#show", as: "user"

  get 'countries/:id/visit', to: "countries#visit"
  

end

app/models/country.rb
class Country < ActiveRecord::Base

  has_many :visits
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :visits
  has_and_belongs_to_many :countries
end

app/models/visit.rb
class Visit < ActiveRecord::Base

  belongs_to :user
  belongs_to :country
  mount_uploader :image, VisitImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def configure_permitted_parameters      
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :age, :email, :password, :password_confirmation, :profile_picture, :description, :favorite_country])

    
  
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :age, :email, :password, :password_confirmation, :profile_picture, :description, :favorite_country])
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy, :visit]

  def visit
    @country.users.push current_user
    redirect_to @country


  end


  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)
    current_user.countries.push(@country)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :user_id, :capital, :population, :currency, :flag, :language, :google_map)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = current_user.visits
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @countries = Country.all
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
       @countries = Country.all
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)
    @visit.user = current_user
    # current_user.visit.push(@visit)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to user_path(current_user), notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to user_path(current_user), notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:user_id, :country_id, :image, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/countries/_form.html.erb
<%= form_for(@country, html: {class: 'form-horizontal'}) do |f| %>

<div class="panel panel-default">
  <div class="panel-body">
    <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% @country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, class: 'col-xs-4 label-control' %>
      <div class="col-xs-8">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :flag, class: 'col-xs-4 label-control' %>
      <div class="col-xs-8">
        <%= f.text_field :flag, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :capital, class: 'col-xs-4 label-control' %>
      <div class="col-xs-8">
        <%= f.text_field :capital , class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :language, class: 'col-xs-4 label-control' %>
      <div class="col-xs-8">
        <%= f.text_field :language , class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :population, class: 'col-xs-4 label-control' %>
      <div class="col-xs-8">
        <%= f.number_field :population, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :currency, class: 'col-xs-4 label-control' %>
      <div class="col-xs-8">
        <%= f.text_field :currency, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :google_map, class: 'col-xs-4 label-control' %>
      <div class="col-xs-8">
        <%= f.text_field :google_map, class: 'form-control' %>
      </div>
    </div>

  </div>
  <div class='panel-footer'>
    <%= f.submit class: 'btn btn-default' %>
  </div>
</div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>


<div class="container">
  <div class="row">
    <div class='col-md-4 col-md-offset-4'>

      <%= render 'form' %>

      <%= link_to 'Show', @country %> |
      <%= link_to 'Back', countries_path %>
    </div>
  </div>
</div>

app/views/countries/index.html.erb
<div class="container">
<h1>
Listing Countries
<%= link_to 'New Country', new_country_path, class: 'btn btn-default' %>
</h1>

<ul>
  <li>
    <% @countries.each do |country| %>
    <ul class="col-md-6 col-sm-12">
      <li><%= image_tag country.flag, width: "200", height: "200" %></li>
      <li><%= link_to country.name, country_path(country) %></li>
    </ul>
    <% end %>
  </li>
</ul>
<br>
</div>

app/views/countries/new.html.erb
<div class="container">
<h1>New Country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>
</div>

app/views/countries/show.html.erb
  <div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @country.flag, width: 300, height: 300 %>
      <h3><%= @country.name %></h3>
    </div>
    <div class="col-md-4">
      <ul>
        <li><strong>Capital:</strong><%= @country.capital %></li>
        <li><strong>Language:</strong><%= @country.language %></li>
        <li><strong>Currency:</strong><%= @country.currency %></li>
        <li><strong>Population:</strong><%= @country.population %></li>
      </ul>
      <%= link_to "Edit", edit_country_path(@country) %>
    </div>
    <div class="col-md-4">
       <iframe src="<%= @country.google_map %>" width="400" height="300" frameborder="0" allowfullscreen></iframe>  
    </div>    
  </div>


<% if @country.visits.any? %>
<h2>Holidays in <%= @country.name %></h2>

<div class="row">
  <% @country.visits.each do |visit| %>
      <div class="col-xs-6">
      <div class="panel panel-default">
        <div class="panel-heading"><a href="/users/<%= visit.user.id %>"><%= visit.user.username %></a></div>
        <div class="panel-body">
          <a href="#">
            <img src="<%= visit.image %>" alt=""  class="image">
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>
</div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>WDI20Project2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Holidays</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "Countries", countries_path %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <a href="/users/<%= current_user.id %>">
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                  <%= current_user.username.capitalize %>
                </a>
                </li>
              <li>
              <%= link_to edit_user_registration_path do %>
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit Profile
              <% end %>
              </li>
              <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span> Log out
              <% end %>
              </li>
              <li role="separator" class="divider"></li>
              <li>
              <%= link_to new_visit_path do %>
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Visit
              <% end %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if flash[:notice] || flash[:alert] %>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
 <% end %>


<main>
<% unless (params[:controller] == "users" && params[:action] == "show") || 
  (params[:controller] == "countries" && params[:action] == "show") ||
  (params[:controller] == "static" && params[:action] == "homepage") 
  %>
  <div id="bannertop"></div>
<% end %>
  <!-- <div class="container"> -->
    <%= yield %>
 <!--  </div> -->
</main>

</body>
</html>

app/views/users/show.html.erb
  
  <div class="row">
     <div class="col-xs-12">
    </div>
</div>
<div class="container" id="profile">

<div class="row" >
   <div class="col-xs-6">
      <img class="profile-picture" src="<%= @user.profile_picture %>">
   </div> 
   <div class="col-xs-6">
      <p><strong>Name:</strong><%= @user.username.capitalize %></p>
      <p><strong>Email:</strong><%= @user.email %></p>
      <p><strong>Age:</strong><%= @user.age %></p>
      <p><strong>Description:</strong><%= @user.description %></p>
      <p><strong>Favorite Country:</strong><%= @user.favorite_country %></p>
   </div>
</div>





<div class="row">
  <% @user.countries.each do |country| %>
    <!-- <ul>
      <li><%= link_to country.name, country_path(country) %></li>
    </ul> -->
  <% end %>
</div>


<div class="row">
  <div class="col-xs-12">
    <h2>Where I've been on holiday</h2>
  </div>
  
<% @user.visits.each do |visit| %>
    <div class="col-xs-6">
      <div class="panel panel-default">
        <div class="panel-heading"><%= link_to visit.country.name, visit_path(visit)%></div>
        <div class="panel-body">
          <a href="#" class="thumbnail">
            <div style="background-image:url('<%= visit.image %>')" class="image"></div>
          </a>
        </div>
         <div class="panel-body">
          <p><%= visit.description %></p>
        </div>
      </div>
    </div>
 <!--  <%= image_tag visit.image %>
  <%= link_to visit.country.name, visit_path(visit) %>
  <%= visit.description %> -->

<% end %>
</div>
</div>

app/views/visits/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for @visit, html: { class: 'form-horizontal'} do |f| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <% if @visit.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

          <ul>
            <% @visit.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <div class="form-group">
          <%= f.label :image, class: 'col-xs-4 label-control' %>
          <div class='col-xs-8'>
          <%= f.file_field :image %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :description, class: 'col-xs-4 label-control' %>
          <div class='col-xs-8'>
          <%= f.text_area :description, class: 'form-control', rows: 6 %>
        </div>
        </div>
        <div class="form-group">
         <%= f.label :country, class: 'col-xs-4 label-control' %>
         <div class='col-xs-8'>
          <select name="visit[country_id]">
            <% @countries.each do |country| %>
            <option value="<%= country.id %>"><%= country.name %></option>
            <% end %>
          </select>
        </div>
         </div>
        <!-- Añado el campo de texto para el comentario de cada visita -->

      </div>
      <div class='panel-footer'>
        <%= f.submit "Save", class: 'btn btn-default' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Visits</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.user_id %></td>
        <td><%= visit.country.name %></td>
        <td><%= link_to 'Show', visit %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<div class="container">

<h1>New Visit</h1>

<%= render 'form' %>

</div>

app/views/visits/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @visit.user.username %>
</p>

<p>
  <strong>Country:</strong>
  <%= @visit.country_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @visit.user.description %>
</p>

<p>
   <b>Visit Image</b>
   <%= image_tag @visit.image.url, width: '200', height: '200' %>
 </p>

<%= link_to 'Edit', edit_visit_path(@visit) %>
<%= link_to 'Delete', visit_path, method: 'delete' %>
<%= link_to 'Back', user_path(current_user) %>
</div>